.\" Copyright 2017 Google Inc.
.\"
.\" Licensed under the Apache License, Version 2.0 (the "License"); you may not
.\" use this file except in compliance with the License.  You may obtain a copy
.\" of the License at:
.\"
.\"     http://www.apache.org/licenses/LICENSE-2.0
.\"
.\" Unless required by applicable law or agreed to in writing, software
.\" distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
.\" WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  See the
.\" License for the specific language governing permissions and limitations
.\" under the License.
.Dd October 22, 2017
.Dt SANDBOXFS 1
.Os
.Sh NAME
.Nm sandboxfs
.Nd A virtual file system for sandboxing
.Sh SYNOPSIS
.Nm
.Op Fl -allow Ar who
.Op Fl -cpu_profile Ar file
.Op Fl -debug
.Op Fl -listen_address Ar host:port
.Op Fl -help
.Op Fl -mem_profile Ar file
.Op Fl -volume_name Ar volume_name
dynamic
.Op Fl -help
.Op Fl -input file
.Op Fl -output file
.Ar mount_point
.Nm
.Op Fl -debug
.Op Fl -help
.Op Fl -volume_name Ar volume_name
static
.Op Fl -help
.Op Fl -read_only_mapping Ar mapping:target
.Op Fl -read_write_mapping Ar mapping:target
.Ar mount_point
.Sh DESCRIPTION
.Nm
is a FUSE file system that exposes a combination of multiple files and
directories from the host's file system in the form of a virtual tree with an
arbitrary layout.
You can think of a sandbox as an arbitrary view into the host's file system with
different access privileges per directory.
.Pp
.Nm
is designed to allow running commands with limited access to the file system by
using the virtual tree as their new root, and to do so consistently across a
variety of platforms.
.Pp
The following general flags are recognized for all commands:
.Bl -tag -width XXXX
.It Fl -allow Ar who
Specifies who should have access to the file system.
.Ar who
must be one of:
.Sq other
to indicate that everyone, including root, can access the file system;
.Sq root
to indicate that only the current user and root can access the file system; and
.Sq self
to indicate that only the current user can access the file system.
.Pp
The default value is
.Sq self
because the standard FUSE configuration does not allow more relaxed
permissions, and it would be a pity if you couldn't run
.Nm
successfully without additional configuration.
To change this behavior, add
.Sq user_allow_other
to
.Pa /etc/fuse.conf
on Linux or set the
.Sq vfs.generic.osxfuse.tunables.allow_other
.Xr sysctl 8
tunable to 1 on macOS.
.Pp
Note that, at least on macOS, you will need to consider granting
.Sq other
permissions if you intend to run signed binaries through the sandbox.
This is because the
.Xr amfid 8
daemon, which implements the signature validation, runs as a different user
and must be able to access the executables.
.It Fl -cpu_profile Ar file
Enables CPU profiling and writes a profile to the given
.Ar file
on exit.
.Pp
This option is incompatible with
.Fl -listen_address
because only one profiling mechanism can be enabled at once.
.It Fl -debug
Logs details about all FUSE operations received and responded to by the FUSE
process to stderr.
.It Fl -listen_address Ar host:port
Starts an HTTP server listening on
.Ar host:port .
The HTTP server exposes the Go pprof endpoints at
.Pa /debug/pprof/ .
If you want to allocate an arbitrary unused port, pass 0 as the port number.
.Pp
This option is incompatible with
.Fl -cpu_profile
and
.Fl -mem_profile
because only one profiling mechanism can be enabled at once.
.It Fl -help
Prints global help details and exits.
.It Fl -mem_profile Ar file
Enables memory profiling and writes a profile to the given
.Ar file
on exit.
.Pp
This option is incompatible with
.Fl -listen_address
because only one profiling mechanism can be enabled at once.
.It Fl -volume_name Ar volume_name
Specifies the name of the mounted volume, which is used by some operating
systems (such as macOS) to display a volume label in the system UI.
.Pp
Default:
.Sq sandboxfs .
.El
.Ss Mapping specifications
The basic concept behind a
.Nm
instance is the
.Em mapping specification .
A mapping specification defines how an arbitrary location within the sandbox
relates to another arbitrary location on the host file system.
Mapping specifications have two components: the
.Em target ,
which is a path to a file or directory into the host file system (i.e. outside
of the mount point), and the
.Em mapping ,
which is an absolute path within the mount point in which the target is exposed.
Note that the target must exist but the mapping may not: in particular,
any path subcomponents of the mapping that have not been previously mapped
within the sandbox will be created as virtual read-only nodes.
.Pp
For example: consider a
.Nm
instance mounted onto
.Pa /mnt
that maps
.Pa /my/custom/bin
to the
.Pa /usr/bin
target.
With this setup,
.Pa /mnt/my/custom/bin
will expose the contents of the real
.Pa /usr/bin
directory.
.Pp
Mapping specifications have a type associated to them, and the following types
are currently supported:
.Bl -tag -width XXXX
.It Read-only
The contents of the target are exposed verbatim at the mapping point and they
cannot be modified through the mount point.
Any write access will result in an
.Dv EPERM .
.It Read/write
The contents of the target are exposed verbatim at the mapping point and they
can be modified at will through the mount point.
Writes through the moint point are applied immediately to the underlying target
directory.
.El
.Ss The dynamic command
The
.Sq dynamic
command mounts a
.Nm
instance on the given
.Ar mount_point
with a view configured at run-time after the mount point is live.
.Nm
will listen for new configuration requests on a specific input file and will
write a confirmation of reconfiguration to another specific output file.
.Pp
A dynamic mount point can be configured any number of times while it is running,
which allows for processes to efficiently change the view of the sandbox at will
without having to remount it.
Closing the input file causes
.Nm
to freeze its configuration and not accept any more requests for
reconfiguration, but the file system will continue to operate normally until
it is either unmounted or signaled.
.Pp
Reconfiguration requests can be issued at any time.
However, it is impossible for
.Nm
to properly deal with ongoing file system operations or with open file handles
in a deterministic manner.
Due to this, the behavior of ongoing file system activity while a
reconfiguration happens is unspecified but can be assumed to be stable (i.e.
.Nm
will not deadlock nor crash).
As a result, it is highly recommended that you only send reconfiguration
requests when you know that the file system is quiescent.
.Pp
The following flags are recognized by this command:
.Bl -tag -width XXXX
.It Fl -help
Prints information specific to this command and exits.
.It Fl -input Ar path
Points to the file from which to read new configuration requests, or
.Sq -
for stdin.
.Pp
Default:
.Sq -
.It Fl -output Ar path
Points to the file to which to write confirmations of reconfiguration,
.Sq -
for stdout.
.Pp
Default:
.Sq -
.El
.Pp
Configuration requests are formatted as a JSON map followed by a single blank
line.
Each entry in the map specifies a single mapping specification, with the
following keys:
.Sq Mapping
and
.Sq Target ,
which define the mapping paths, and
.Sq Writable ,
which if set to true indicates a read/write mapping.
.Pp
Once
.Nm
accepts a valid reconfiguration request and the file system is fully
reconfigured, the single line
.Sq Done
is written to the output file.
.Ss The static command
The
.Sq static
command mounts a
.Nm
instance on the given
.Ar mount_point
with a view configured at startup time via command-line flags.
.Pp
The following flags are recognized by this command:
.Bl -tag -width XXXX
.It Fl -help
Prints information specific to this command and exits.
.It Fl -read_only_mapping Ar mapping:target
Registers a new read-only mapping.
This flag can be given an arbitrary number of times as long as the same
.Ar mapping
is not repeated.
See the
.Sx Mapping specifications
subsection for details on how a mapping is specified.
.It Fl -read_write_mapping Ar mapping:target
Same as
.Fl -read_only_mapping
but configures a read/write mapping.
.El
.Sh EXIT STATUS
.Nm
exits with 0 if the file system was both mounted and unmounted cleanly; 1 on a
controlled error condition encountered during the execution of a command; or 2
on a usage error.
.Pp
Sending a termination signal to
.Nm
will cause the file system to exit in a controlled manner, ensuring that the
mount point is released.
If the file system is busy, the signal will be queued until all open file
descriptors on the file system are released at which point the file system
will try to exit cleanly again.
Note that, due to the nature of signal handling in Go (which is the language
in which
.Nm
is implemented), the reception of a signal will cause
.Nm
to return 1 instead of terminating with a signal condition.
.Sh EXAMPLES
The following example configures a static sandbox that maps the whole host's
file system but clears
.Pa /tmp
to point into a sandbox-specific writable directory:
.Bd -literal -indent
sandboxfs \\
    --read_only_mapping=/:/ \\
    --read_write_mapping=/tmp:/tmp/fresh-tmp \\
    /mnt
.Ed
.Pp
This same configuration can be expressed as the following JSON data when using
the dynamic mode:
.Bd -literal -indent
[
    {"Mapping": "/tmp", "Target": "/tmp/fresh-tmp", "Writable": false},
    {"Mapping": "/", "Target": "/", "Writable": true}
]
.Ed
.Sh AUTHORS
.An -nosplit
The
.Nm
package was originally developed by
.An Pallav Agarwal
.Aq pallavag@google.com
and
.An Julio Merino
.Aq jmmv@google.com .
.Sh BUGS
The following are known limitations of
.Nm :
.Bl -bullet
.It
Hard links are not supported.
.It
On macOS, mapping the same external file or directory under two different
locations within the mount point results in undefined behavior.
Writes may not be reflected at both mapped locations at the same time, which
can lead to data corruption.
This is true even for read-only mappings because each separate view within
the mount point may have cached different contents, returning different data
than what's truly on disk.
.It
The
.Fl allow Ar root
setting does not work on Linux; use
.Fl allow Ar other
as the alternative.
See https://github.com/bazil/fuse/issues/144 for details.
.It
It is currently impossible to terminate
.Nm
cleanly while the file system is busy.
Signals received while the file system is in use will be queued as described in
.Sx EXIT STATUS
and fatal signals will cause
.Nm
to leak the mount point (possibly irrecoverably without a reboot because of
kernel bugs).
.El
