#! /bin/sh
# Copyright 2016 Google Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may not
# use this file except in compliance with the License.  You may obtain a copy
# of the License at:
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  See the
# License for the specific language governing permissions and limitations
# under the License.

exec 1>&2

# Obtain the list of files from the index (i.e. the files to be committed).
# From the list, resolve renames to their target.
index_files="$(git status --porcelain --untracked-files=no \
    | grep '^[MARC]' | cut -c 4- | sed -e 's,^.* -> ,,')"

if [ -n "${index_files}" ]; then
  echo "Linting changed files..."
  bazel run //admin/lint -- ${index_files} || exit 1
fi
